image: node:latest

pages:
  stage: deploy
  script:
  - rm -rf public
  - mkdir public
  - npm i
  - node createdevices.js
  - npm run build-ci-only
  artifacts:
    paths:
    - public
  only:
  - master
