image: node:latest

pages:
  stage: deploy
  script:
  - curl -sL 'https://gitlab.com/api/v4/projects/10582521/jobs/artifacts/master/download?job=Supported%20Devices' -o tmp.zip
  - unzip -p tmp.zip 'Supported Devices.csv' > ./static/data/supported_devices.csv
  - rm tmp.zip
  - npm i
  - npm run build-ci  
  artifacts:
    paths:
    - public
  only:
  - master
